"project_dir: /home/vadams/Projects/entity-linking-research/NeMo/examples/nlp/entity_linking\n\
  name: SelfAlignmentPretrainingForMedicalEntityLinking\ntrainer:\n  gpus: 1\n  num_nodes:\
  \ 1\n  max_epochs: 2\n  max_steps: null\n  accumulate_grad_batches: 1\n  precision:\
  \ 16\n  amp_level: O1\n  accelerator: ddp\n  gradient_clip_val: 0.0\n  log_every_n_steps:\
  \ 1\n  val_check_interval: 1000\n  checkpoint_callback: false\n  logger: false\n\
  model:\n  nemo_path: ${project_dir}\n  max_seq_length: 128\n  language_model:\n\
  \    pretrained_model_name: cambridgeltl/SapBERT-from-PubMedBERT-fulltext\n    config_file:\
  \ null\n    config: null\n    lm_checkpoints: null\n  tokenizer:\n    tokenizer_name:\
  \ bert-base-uncased\n    vocab_file: null\n    tokenizer_model: null\n    do_lower_case:\
  \ true\n  train_ds:\n    data_file: ${project_dir}/data/umls_train_pairs.txt\n \
  \   max_seq_length: ${model.max_seq_length}\n    batch_size: 128\n    shuffle: true\n\
  \    num_workers: 2\n    pin_memory: false\n    drop_last: false\n  validation_ds:\n\
  \    data_file: ${project_dir}/data/umls_validation_pairs.txt\n    max_seq_length:\
  \ ${model.max_seq_length}\n    batch_size: 128\n    shuffle: false\n    num_workers:\
  \ 2\n    pin_memory: false\n    drop_last: false\n  optim:\n    name: adam\n   \
  \ lr: 3.0e-05\n    weight_decay: 0.0\n    sched:\n      name: CosineAnnealing\n\
  \      warmup_steps: null\n      warmup_ratio: 0.1\n      min_lr: 0.0\n      last_epoch:\
  \ -1\nindex:\n  dims: 256\n  nlist: 300\n  query_num_factor: 20\n  index_save_name:\
  \ ${project_dir}/medical_entity_linking_index\n  index_batch_size: 1000\n  dataset:\n\
  \    name: umls\n    data_file: ${project_dir}/data/umls_index_concepts.txt\n  \
  \  max_seq_length: ${model.max_seq_length}\n    batch_size: 128\n    shuffle: false\n\
  \    num_workers: 2\n    pin_memory: false\n    drop_last: false\n  idx_to_id: ${project_dir}/data/idx_to_id.pkl\n\
  \  id_to_string: ${project_dir}/data/id_to_string.pkl\n  concept_id_save_name: ${project_dir}/data/concept_ids.pkl\n\
  \  embedding_save_name: ${project_dir}/data/medical_concept_embeddings.hdf5\n  pca_embeddings_save_name:\
  \ ${project_dir}/data/medical_concept_reduced_${index.dims}dim_embeddings.hdf5\n\
  \  apply_pca: true\n  pca:\n    input_dim: 756\n    output_dim: ${index.dims}\n\
  \    sample_fraction: 0.5\n    pca_save_name: ${project_dir}/${index.pca.input_dim}_to_${index.pca.output_dim}_pca_model.pkl\n\
  exp_manager:\n  exp_dir: ${project_dir}/medical_entity_linking_experiments\n  name:\
  \ SelfAlignmentPretrainingUMLS\n  create_tensorboard_logger: true\n  create_checkpoint_callback:\
  \ true\nhydra:\n  run:\n    dir: .\n  job_logging:\n    root:\n      handlers: null\n"
